# Generated by Django 4.1.5 on 2023-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_comments_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='Anon', max_length=100),
            preserve_default=False,
        ),
    ]
