# Generated by Django 4.1.5 on 2023-03-05 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_comments_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='date_posted',
            new_name='created_on',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='title',
        ),
    ]
