# Generated by Django 4.1.5 on 2023-03-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
