# Generated by Django 4.1.5 on 2023-03-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_comments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='posts'),
        ),
    ]
