# Generated by Django 4.1.5 on 2023-03-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_posts_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=300, upload_to='posts', width_field=300),
        ),
    ]
