# Generated by Django 4.1.5 on 2023-03-06 22:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_greenposts_image_alter_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('greenposts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greencomments', to='website.posts')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
