# Generated by Django 4.1.5 on 2023-03-07 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0015_posts_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenposts',
            name='likes',
            field=models.ManyToManyField(related_name='greenpost_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
