# Generated by Django 4.1.5 on 2023-03-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_greenposts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='greencomments',
            name='greenposts',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='GreenComments',
        ),
    ]
